# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - build/**
    - android/**
    - ios/**
  errors:
    missing_return: error
    must_be_immutable: warning
    must_call_super: error
    invalid_use_of_protected_member: error
    parameter_assignments: warning

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_print: false
    prefer_single_quotes: true
    unawaited_futures: true
    prefer_is_empty: true
    prefer_is_not_empty: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
