org.gradle.jvmargs=-Xmx2048M -XX:HeapBaseMinAddress=1g -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
kotlin.daemon.jvmargs=-Xmx256m -XX:HeapBaseMinAddress=1g -Dfile.encoding=UTF-8
