org.gradle.jvmargs=-Xmx3072M -XX:HeapBaseMinAddress=1g -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.workers.max=2
kotlin.daemon.jvmargs=-Xmx512m -XX:HeapBaseMinAddress=1g -Dfile.encoding=UTF-8
