// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'rotable.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Rotable _$RotableFromJson(Map<String, dynamic> json) => Rotable(
      id: json['id'] as String?,
      materialCode: json['materialCode'] as String?,
      materialName: json['materialName'] as String?,
      materialModel: json['materialModel'] as String?,
      batchNum: json['batchNum'] as String?,
      dwgNo: json['dwgNo'] as String?,
      unitNum: json['unitNum'] as String?,
      compositionsName: json['compositionsName'] as String?,
      serialNum: json['serialNum'] as String?,
      producerName: json['producerName'] as String?,
      productNum: json['productNum'] as String?,
      capitalNum: json['capitalNum'] as String?,
      capitalType: json['capitalType'] as int?,
      productionDate: json['productionDate'] as String?,
      putinQualitySignDate: json['putinQualitySignDate'] as String?,
      qualityCertificationDate: json['qualityCertificationDate'] as String?,
      qualityCertificationLocation:
          json['qualityCertificationLocation'] as String?,
      materialState: json['materialState'] as int?,
      materialStateDetail: json['materialStateDetail'] as String?,
      repairCycle: json['repairCycle'] as String?,
      remark: json['remark'] as String?,
      lastUpdateDatetime: json['lastUpdateDatetime'] as String?,
      createDatetime: json['createDatetime'] as String?,
      maintenanceCycle: json['maintenanceCycle'] as int?,
      expirationDate: json['expirationDate'] as String?,
      trainModels: json['trainModels'] as String?,
      rootStoreplaceId: json['rootStoreplaceId'] as String?,
      storeplaceId: json['storeplaceId'] as String?,
      storelocationId: json['storelocationId'] as String?,
      lastMaintenanceDate: json['lastMaintenanceDate'] as String?,
      storeState: json['storeState'] as int?,
      truckLocation: json['truckLocation'] as String?,
      locationRemark: json['locationRemark'] as String?,
      putinSource: json['putinSource'] as String?,
      rubberNodeDate: json['rubberNodeDate'] as String?,
      storePlaceName: json['storePlaceName'] as String?,
      storeLocationName: json['storeLocationName'] as String?,
      rootStorePlaceName: json['rootStorePlaceName'] as String?,
    );

Map<String, dynamic> _$RotableToJson(Rotable instance) => <String, dynamic>{
      'id': instance.id,
      'materialCode': instance.materialCode,
      'materialName': instance.materialName,
      'materialModel': instance.materialModel,
      'batchNum': instance.batchNum,
      'dwgNo': instance.dwgNo,
      'unitNum': instance.unitNum,
      'compositionsName': instance.compositionsName,
      'serialNum': instance.serialNum,
      'producerName': instance.producerName,
      'productNum': instance.productNum,
      'capitalNum': instance.capitalNum,
      'capitalType': instance.capitalType,
      'productionDate': instance.productionDate,
      'putinQualitySignDate': instance.putinQualitySignDate,
      'qualityCertificationDate': instance.qualityCertificationDate,
      'qualityCertificationLocation': instance.qualityCertificationLocation,
      'materialState': instance.materialState,
      'materialStateDetail': instance.materialStateDetail,
      'repairCycle': instance.repairCycle,
      'remark': instance.remark,
      'lastUpdateDatetime': instance.lastUpdateDatetime,
      'createDatetime': instance.createDatetime,
      'maintenanceCycle': instance.maintenanceCycle,
      'expirationDate': instance.expirationDate,
      'trainModels': instance.trainModels,
      'rootStoreplaceId': instance.rootStoreplaceId,
      'storeplaceId': instance.storeplaceId,
      'storelocationId': instance.storelocationId,
      'lastMaintenanceDate': instance.lastMaintenanceDate,
      'storeState': instance.storeState,
      'truckLocation': instance.truckLocation,
      'locationRemark': instance.locationRemark,
      'putinSource': instance.putinSource,
      'rubberNodeDate': instance.rubberNodeDate,
      'storePlaceName': instance.storePlaceName,
      'storeLocationName': instance.storeLocationName,
      'rootStorePlaceName': instance.rootStorePlaceName,
    };
